# Generated by Django 5.0.3 on 2024-04-18 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cookiepreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cookiePreferences',
            new_name='CookiePreference',
        ),
    ]
