# Generated by Django 5.0.3 on 2024-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_cookiepreferences_cookiepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiepreference',
            name='essential_text',
            field=models.TextField(blank=True, verbose_name='Description des cookies essentiels'),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='functionality_text',
            field=models.TextField(blank=True, verbose_name='Description des cookies de fonctionnalité'),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='performance_text',
            field=models.TextField(blank=True, verbose_name='Description des cookies de performance'),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='tracking_text',
            field=models.TextField(blank=True, verbose_name='Description des cookies de suivi'),
        ),
    ]
