# Generated by Django 5.0.3 on 2024-04-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cookiepreference_essential_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiepreference',
            name='essential_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cookiepreference',
            name='functionality_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cookiepreference',
            name='performance_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cookiepreference',
            name='tracking_text',
            field=models.TextField(blank=True),
        ),
    ]
