# Generated by Django 5.0.3 on 2024-04-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_cookiepreference_essential_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiepreference',
            name='user',
        ),
    ]
