# Generated by Django 5.0.3 on 2024-04-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cookiepreference_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiepreference',
            name='user',
        ),
    ]
