# Generated by Django 5.0.3 on 2024-04-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musique',
            name='fichier',
            field=models.FileField(upload_to='media/sons/'),
        ),
    ]
