# Generated by Django 5.0.3 on 2024-04-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_musique_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musique',
            name='fichier',
            field=models.FileField(upload_to='sons/'),
        ),
    ]
