# Generated by Django 5.0.3 on 2024-03-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_produit_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
