# Generated by Django 5.0.3 on 2024-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_panier_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='client',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='client_date',
        ),
        migrations.AddField(
            model_name='commande',
            name='client_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
