# Generated by Django 5.0.3 on 2024-03-18 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_publier_article_slug_article_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publier',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
