# Generated by Django 5.0.3 on 2024-03-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_commentaire_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.CharField(max_length=100),
        ),
    ]
