# Generated by Django 5.0.3 on 2024-03-21 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_categorie_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_articles', to='blog.categorie'),
            preserve_default=False,
        ),
    ]
