# Generated by Django 5.0.3 on 2024-03-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_category_categorie_remove_article_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publier',
            new_name='publication',
        ),
    ]
